### ISSUE TITLE
Morning session peer-to-peer code review.

### ISSUE THREAD

**Issue by enoqueJonas** [enoqueJonas/Portfolio#13]
Peer-to-peer code review.

**Comment by jellywiz** [comment]
Great job at getting this far @enoqueJonas 
there are a few things I wanted to mention

- I believe there is no need to create separate CSS files for your design, i think it would have been better if you just stick with one CSS file.
- In your code I don't think you have used media query for different screens i think rather than using 2 different CSS files you could have used media query so the code wont be complicated as i mentioned above.
- It is not advisable to use IDs as CSS selectors because if another element in the page uses the same/similar style, you would have to write the same CSS again. Even if you don't have more than one element with that style right now, it might come later. Hence it is always advisable to use class.

**Comment by AbeeraTahir** [comment]
Hi @enoqueJonas,

You really did a great job. You have spent a lot of time and effort. I really appreciate that. However, there are some points that I want to highlight about design:

- There is too much margin from the top in the about me section, kindly reduce it and make it according to Figma design.
- Kindly add some gap between the about me section and the languages section, just like Figma.

**Comment by HevarKas** [comment]
Hi @enoqueJonas 

- please remove the extra margin it will be more better.
- i think it's better if you use one file for css.

### thanks
