### ISSUE TITLE
Microverse peer-to-peer code review session

### ISSUE THREAD

**Issue by enoqueJonas** [enoqueJonas/Portfolio#8]
Morning session feedback on the project.

**Comment by jellywiz** [comment]
- It is not advisable to use IDs as CSS selectors because if another element in the page uses the same/similar style, you would have to write the same CSS again. Even if you don't have more than one element with that style right now, it might come later. Hence it is always advisable to use class.
- There are some comments in Styless.css and I believe that comments should be deleted so that there is no complexity of the code

**Comment by Boku52500** [comment]
- PR should be more descriptive to understand what was changed in the code.

**Comment by ivanmvh** [comment]
hello

**Comment by ivanmvh** [comment]
I think that sometime comment are needed.
